# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

def fibonacci_sequence(max, seq = [1,2])
  seq << (seq[-2] + seq[-1])
  seq[-1] >= max ? seq[0..-2] : fibonacci_sequence(max, seq)
end

def problem_2_solver(max = 4_000_000)
  all_terms  = fibonacci_sequence(max)
  even_terms = all_terms.select{ |i| i if i.even? }
  even_terms.inject(:+)
end
